[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

[context.production.environment]
  REACT_APP_API_URL = "https://proofmaster-api.onrender.com"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://proofmaster-api.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
